import {useEffect, useState} from 'react'
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

/**
 * Switcher to show correct view depending on status of data fetch
 * @property {Object} data
 * @property {Object} error
 * @property {Boolean} isPending
 */
function CustomerData({data, error, isPending}) {
  if (isPending) return 'Loading'
  else if (error) return `Something went wrong: ${error.message}`
  else if (data) return (
    <div>{JSON.stringify(data, null)}</div>
    )
  return null
}

export default function Home() {
  const [customers, setCustomers] = useState(null)
  const [error, setError] = useState(null)
  const [isPending, setIsPending] = useState(false)
  // TODO: retry button if error
  useEffect(() => {
    setIsPending(true)
    fetch('https://rawgit.com/wvchallenges/se-exp-challenge-invoice/master/settings.json')
    .then(response => response.json())
    .then(data => setCustomers(data.customers))
    .catch(err =>
      // console.error(err)
      setError(err)
    )
    .finally(() => setIsPending(false))
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <div>
          <CustomerData data={customers} error={error} isPending={isPending} />
          </div>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By
            </a>
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
